Vaga de Estágio
bempaggo/developer-challenge pull request #27
Opened 2023-06-28 03:16 UTC by marquescaroline

Olá, sou a Caroline, estou estudando Analise e Desenvolvimento de Sistemas, fiz alguns cursos na área de programação, e estou procurando uma oportunidade para demonstrar meu potencial.

**O que eu fiz?**
Alterei o código utilizando o conceito de POO e criei testes unitários utilizando Junit.
Fiz o projeto em linguagem Java utilizando o Intellij por me sentir mais confortável mas estou aberta a aprender novos frameworks e IDEs caso necessário. 

Aprendi bastante realizando este desafio e estou a disposição para qualquer duvida sobre minha implementação.

email: carolmarques614@gmail.com
linkedin: https://www.linkedin.com/in/caroline-marques1998/

2023-07-02 14:17 UTC, douglashiura requested changes

2023-07-02 14:17 UTC, douglashiura commented on jogo-oito/src/main/java/chat/gpt/Rules.java
> +                ((movedPiece.getPosition()+3 == emptyPiece.getPosition()) ||
Obrigado Caroline por ter tentado resolver o desafio.
Dos pull request que vi ate agora para estágio, o teu código é um dos que mais tenta usar poo. 
Contudo, aparentemente, não domina de fato o paradigma, eu percebo aqui que há falta de abstração na classe Board. Devido à falta de abstração decorre que vc tenta resolver isso com procedimentos, regras ou até mesmo com outros paradigmas.
Dica: 
Os objetos trocam mensagens. 
E as classe determinam a responsabilidade do objeto.

Atenciosamente.

2023-07-02 20:51 UTC, marquescaroline commented on jogo-oito/src/main/java/chat/gpt/Rules.java
> +                ((movedPiece.getPosition()+3 == emptyPiece.getPosition()) ||
Agradeço pelo seu comentário! 
Gostaria de saber se existe a possibilidade de fazer um novo pull request dando atenção para as dicas que vc citou e tentando melhorar meu código?

Atenciosamente,
Caroline.

2023-07-14 21:39 UTC, douglashiura commented on jogo-oito/src/main/java/chat/gpt/Rules.java
> +                ((movedPiece.getPosition()+3 == emptyPiece.getPosition()) ||
Boa noite.
Sim existe. Recebemos quantos pull request encaminhar para a gente, porém tente ver os outros pull requests recusados para não encaminhar problemas recorrentes.

Atenciosamente.

2024-01-31 15:18 UTC, closed without merging