Development Challenge - Desenvolvedor Sênior
bempaggo/developer-challenge pull request #49
Opened 2023-10-12 00:43 UTC by Gabriel0297

Refatorei o código deixando mais clean possível, tentando respeitar POO e aplicando Padrões de Projetos de Software.
Na classe Matrix, ao tentar diminuir o código acabei me apoiando em números mágicos, fazendo assim com que a criação da matriz fosse engessada em 3x3, pois tanto os números quanto as regras, ficaram personalizadas para esse formato. Dessa forma pensei em criar outra lógica que me permitisse fazer o jogo ser ainda mais dinâmico, mas por causa do tempo não implementei, contudo irei propor uma nova versão que irá contemplar isso.

2023-10-12 16:06 UTC, Gabriel0297 commented
Dei um commit implementando a teoria de matriz quadrada, dessa forma o jogo consegue ser mais dinâmico, para toda matriz quadrada de ordem n diferente de 1, já que o intuito do jogo é ordenar os números. Decidi não externalizar essa criação de ordem diferente de 3, já que o jogo na vida real é uma matriz quadrada de ordem  3. Mantive a ideia de trabalhar com adjacente horizontal e vertical, mas para criar de forma dinâmica utilizei a teoria do múltiplo da ordem da matriz.

2023-10-13 16:19 UTC, douglashiura requested changes

2023-10-13 16:19 UTC, douglashiura commented on jogo-oito/src/main/java/game/model/Matrix.java
> +    		if (!rest.equals(order -1))
Boa Tarde,
Objetos devem trocar mensagens.
O objetivo é uso de POO, o uso de programação funcional atrapalha na coesão.

Att.

2023-10-13 17:25 UTC, Gabriel0297 commented on jogo-oito/src/main/java/game/model/Matrix.java
> +    		if (!rest.equals(order -1))
Boa tarde, 
Esse seria o único ponto onde ocorre esse problema? E é possível enviar outra solução para contar nesse processo?

2023-10-15 21:13 UTC, douglashiura commented on jogo-oito/src/main/java/game/model/Matrix.java
> +    		if (!rest.equals(order -1))
Todos onde usas o paradigma funcional (seção 4, do readme, Caso rejeitado, apontaremos apenas um problema.).
Sim, mas reveja os outros pull requestes e o readme. Sugestão, reduza o volume de código.

2023-10-17 19:03 UTC, closed without merging